"""recreate currency table

Revision ID: 06029a81ca68
Revises: 969e5ca0a11f
Create Date: 2026-03-02 20:44:03.288618

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '06029a81ca68'
down_revision: Union[str, None] = '969e5ca0a11f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currencyrates',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('bank_name', sa.String(), nullable=False),
        sa.Column('bank_en', sa.String(), nullable=False),
        sa.Column('link', sa.String(), nullable=False),
        sa.Column('usd_buy', sa.Float(), nullable=False),
        sa.Column('usd_sell', sa.Float(), nullable=False),
        sa.Column('eur_buy', sa.Float(), nullable=False),
        sa.Column('eur_sell', sa.Float(), nullable=False),
        sa.Column('update_time', sa.String(), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('bank_name'),
        sa.UniqueConstraint('bank_en'),
        sa.UniqueConstraint('link')
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('currencyrates')
    # ### end Alembic commands ###
