"""add is_active, last_seen_at to currencyrates

Revision ID: 70c5c85af7e8
Revises: 06029a81ca68
Create Date: 2026-06-26 11:30:05.727586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70c5c85af7e8'
down_revision: Union[str, None] = '06029a81ca68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currencyrates', sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('currencyrates', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###

    op.execute("UPDATE currencyrates SET is_active = true, last_seen_at = now() WHERE is_active IS NULL")

    op.alter_column('currencyrates', 'is_active', nullable=False)
    op.alter_column('currencyrates', 'last_seen_at', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('currencyrates', 'is_active')
    op.drop_column('currencyrates', 'last_seen_at')
    # ### end Alembic commands ###
