"""add currency table

Revision ID: 969e5ca0a11f
Revises: 2e33ab469ced
Create Date: 2026-02-26 18:41:09.112195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '969e5ca0a11f'
down_revision: Union[str, None] = '2e33ab469ced'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currencyrates',
    sa.Column('bank_name', sa.String(), nullable=False),
    sa.Column('bank_en', sa.String(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('usd_buy', sa.Float(), nullable=False),
    sa.Column('usd_sell', sa.Float(), nullable=False),
    sa.Column('eur_buy', sa.Float(), nullable=False),
    sa.Column('eur_sell', sa.Float(), nullable=False),
    sa.Column('update_time', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bank_en'),
    sa.UniqueConstraint('bank_name'),
    sa.UniqueConstraint('link')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('currencyrates')
    # ### end Alembic commands ###
