# docker compose build - используем для сборки образов, если меняли содежримое любого файла приложения
# docker compose up - используем для запуска образов, если изменили только содержимое docker-compose

services:
  db:
    image: postgres:17
    container_name: converter_db
    env_file: # Файл с переменными окружения (Вместо environment)
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5484:5432"

  app:
    image: converter_image
    build: .
    container_name: converter_app
    ports:
      - "8940:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data: